# Generated by Django 4.0.3 on 2022-03-31 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
